(* Differential operators are encoded as polynomials in commuting placeholders
   for partial derivatives, but multiplication uses the Leibniz rule. The input
   identities must be established independently, with every boundary retained. *)
operatorNormalize[p_,ds_]:=Total[Times@@(ds^First[#]) Together[Last[#]]& /@ CoefficientRules[Expand[p],ds]];
operatorLead[p_,ds_]:=First[CoefficientRules[p,ds,DegreeReverseLexicographic]];
operatorMonic[p_,ds_]:=If[zero[p],0,operatorNormalize[p/Last[operatorLead[p,ds]],ds]];
operatorLeftDerivative[alpha_List,p_,ds_,xs_]:=Module[{terms=CoefficientRules[p,ds],gammas=Tuples[Range[0,#]& /@ alpha]},
 operatorNormalize[Total[Flatten[Table[
   Times@@MapThread[Binomial,{alpha,gamma}] Fold[Function[{c,iv},D[c,{xs[[iv]],gamma[[iv]]}]],Last[term],Range[Length[xs]]]
    Times@@(ds^(alpha-gamma+First[term])),{term,terms},{gamma,gammas}]]],ds]];
operatorRemainder[p_,basis_,ds_,xs_]:=Module[{q=operatorNormalize[p,ds],r=0,lead,k,gl,term},
 While[!zero[q],lead=operatorLead[q,ds];
  k=SelectFirst[Range[Length[basis]],And@@Thread[First[operatorLead[basis[[#]],ds]]<=First[lead]]&,Missing["NoDivisor"]];
  If[MissingQ[k],term=Last[lead] Times@@(ds^First[lead]);r+=term;q=operatorNormalize[q-term,ds],
   gl=operatorLead[basis[[k]],ds];q=operatorNormalize[q-Last[lead]/Last[gl] operatorLeftDerivative[First[lead]-First[gl],basis[[k]],ds,xs],ds]]];
 operatorNormalize[r,ds]];

Options[TopAnnihilatorRankBound]={"TimeLimit"->300,"MaxPairs"->10000,"MaxQuotientDimension"->100000};
TopAnnihilatorRankBound[operators_List,ds_List,xs_List,OptionsPattern[]]:=Module[
 {basis={},pairs={},done=0,i,j,li,lj,lcm,s,r,stair,result,t0=AbsoluteTime[]},
 If[Length[ds]=!=Length[xs]||ds==={}||!DuplicateFreeQ[Join[ds,xs]]||!VectorQ[Join[ds,xs],MatchQ[#,_Symbol]&]||
  !AllTrue[operators,PolynomialQ[#,ds]&&FreeQ[#,_Real]&],Return[fail["AnnihilatorInput","Use exact differential operators with distinct coordinate and derivative symbols."]]];
 result=TimeConstrained[Catch[
  Do[r=operatorRemainder[op,basis,ds,xs];If[!zero[r],AppendTo[basis,operatorMonic[r,ds]]],{op,operators}];
  pairs=Subsets[Range[Length[basis]],{2}];
  While[pairs=!={},If[done++>=OptionValue["MaxPairs"],Throw[fail["AnnihilatorPairLimit","Differential Groebner calculation reached its pair limit; no incomplete rank is returned."]]];
   {i,j}=First[pairs];pairs=Rest[pairs];li=First[operatorLead[basis[[i]],ds]];lj=First[operatorLead[basis[[j]],ds]];
   lcm=MapThread[Max,{li,lj}];
   s=operatorLeftDerivative[lcm-li,basis[[i]],ds,xs]-operatorLeftDerivative[lcm-lj,basis[[j]],ds,xs];
   r=operatorRemainder[s,basis,ds,xs];
   If[!zero[r],AppendTo[basis,operatorMonic[r,ds]];pairs=Join[pairs,Table[{k,Length[basis]},{k,Length[basis]-1}]]]];
  stair=criticalStaircase[basis,ds,OptionValue["MaxQuotientDimension"]];
  If[FailureQ[stair],Throw[fail["UnboundedDerivativeStaircase","The supplied identities do not yet bound every derivative direction.",<|"DifferentialGroebnerBasis"->basis|>]]];
  <|"Status"->"ConditionalAnnihilatorBound","UpperBound"->stair["Dimension"],"InputOperators"->operators,
   "DifferentialGroebnerBasis"->basis,"DerivativeVariables"->ds,"KinematicVariables"->xs,
   "StandardDerivativeExponents"->stair["Exponents"],"PairsReduced"->done,
   "LeibnizRuleUsed"->True,"Scope"->"Cyclic space generated by the specified top",
   "Condition"->"Every supplied operator must annihilate the actual top, including all lower-loop contact terms",
   "OperatorIdentitiesVerified"->False,"Seconds"->AbsoluteTime[]-t0|>
 ],OptionValue["TimeLimit"],fail["AnnihilatorTimeout","Differential Groebner computation timed out; no rank is inferred."]];result];

topDerivativeAnsatz[f_,top_,order_Integer]:=Module[{n=Length[f["Variables"]],exponents,raw={},parent,i,d,k,failed=None},
 exponents=SortBy[Select[Tuples[Range[0,order],n],Total[#]<=order&],{Total[#],#}&];
 Do[If[Total[alpha]===0,AppendTo[raw,top],
   i=First[FirstPosition[alpha,_?Positive]];parent=alpha-UnitVector[n,i];k=First[FirstPosition[exponents,parent]];
   d=DifferentiateIntegrals[f,{raw[[k]]}];If[FailureQ[d],failed=d;Break[]];
   AppendTo[raw,First[d["Rows"][f["Variables"][[i]]]]]],{alpha,exponents}];
 If[FailureQ[failed],failed,<|"Exponents"->exponents,"Expressions"->raw|>]];

(* Exact containment plus a modular equal-rank witness certifies row-space
   equality over the rational-function field. The witness is obtained using
   FiniteFlow; no numerical RowReduce or deleted boundary column is used. *)
topBoundRowSpaceCertificate[f_,pool_,reduction_,point_]:=Module[
 {rows=canonExpr[f,#]& /@ pool,rules,ps,triangular,res,graph,in,node,learn,values,nrules,rank,cols=reduction["ColumnOrder"]},
 rules=Select[reduction["Rules"],!zero[First[#]-Last[#]]&];ps=First /@ rules;
 triangular=DuplicateFreeQ[ps]&&Intersection[ps,Join[support[Last /@ rules],sources[Last /@ rules]]]==={};
 res=canonicalLinear /@ (rows/.Dispatch[rules]);
 If[!triangular||!AllTrue[res,#===0&],Return[fail["TopBoundExactRowSpace","Exact containment in the independent reconstructed relation rows failed."]]];
 FiniteFlow`FFNewGraph[graph];FiniteFlow`FFGraphInputVars[graph,in,f["Variables"]];
 FiniteFlow`FFAlgSparseSolver[graph,node,{in},f["Variables"],#==0& /@ rows,cols,"NeededVars"->cols];
 FiniteFlow`FFSolverSparseOutput[graph,node];FiniteFlow`FFGraphOutput[graph,node];learn=FiniteFlow`FFSparseSolverLearn[graph,cols];
 If[!ListQ[learn],FiniteFlow`FFDeleteGraph[graph];Return[fail["TopBoundRankLearn","Could not construct a rank witness."]]];
 values=FiniteFlow`FFGraphEvaluateMany[graph,{point},"NThreads"->1];FiniteFlow`FFDeleteGraph[graph];
 If[!MatchQ[values,{_List}]||!VectorQ[First[values],IntegerQ],Return[fail["TopBoundRankPoint","The generic rank witness point was singular."]]];
 nrules=FiniteFlow`FFSparseSolverSol[First[values],learn];rank=Length[nrules];
 If[rank=!=Length[rules],Return[fail["TopBoundRankMismatch","Original and reconstructed relation ranks disagree."]]];
 <|"ExactRationalRowSpacesEqual"->True,"ExactOriginalPoolContainment"->True,"Rank"->rank,
  "Point"->point,"Prime"->FiniteFlow`FFPrimeNo[0],"VerificationPoints"->1,"AllBoundaryColumnsRetained"->True|>];

Options[TopDerivativeBound]={"MaxDerivativeOrder"->2,"CountScope"->"HighestLoopModuloBoundary","Workers"->1,"KernelExecutable"->Automatic,
 "NumericalVerificationPoint"->Automatic,"TimeLimit"->300,"ProgressFunction"->Print};
TopDerivativeBound[f_Association,top_,OptionsPattern[]]:=Module[
 {order=OptionValue["MaxDerivativeOrder"],scope=OptionValue["CountScope"],ansatz,pool,red,raw,images,countImages,atoms,matrix,cvars,rules,free,vectors,residuals,ds,operators,bound,proof,point,report=OptionValue["ProgressFunction"],base,t0=AbsoluteTime[]},
 If[!MemberQ[$Packages,"FiniteFlow`"],Return[fail["FiniteFlowRequired","TopDerivativeBound requires FiniteFlow for IBP and annihilator relations."]]];
 If[!IntegerQ[order]||order<1||f["Variables"]==={}||!FiniteIntegralQ[f,top],Return[fail["TopBoundInput","Supply a verified finite top, kinematic variables and a positive derivative-ansatz order."]]];
 If[!MemberQ[{"HighestLoopModuloBoundary","FullTopCyclicSpace"},scope],Return[fail["TopBoundScope","Choose HighestLoopModuloBoundary or FullTopCyclicSpace."]]];
 ansatz=topDerivativeAnsatz[f,top,order];If[FailureQ[ansatz],Return[ansatz]];raw=ansatz["Expressions"];
 point=Replace[OptionValue["NumericalVerificationPoint"],Automatic:>If[Length[f["Variables"]]===2,{7338376896737913617,7718278679044643367},Prime[Range[Length[f["Variables"]]]+10000]]];
 If[!VectorQ[point,IntegerQ]||Length[point]=!=Length[f["Variables"]],Return[fail["TopBoundPoint","Supply one integer point with one coordinate per kinematic variable."]]];
 If[report=!=None,report[<|"Event"->"TopDerivativeAnsatz","MaximumOrder"->order,"Queries"->Length[raw],"DECampaignRun"->False|>]];
 pool=GenerateSystem[f,support[raw],"SeedGeometry"->"InverseTargets","InverseOperatorPolicy"->"Complete",
  "Workers"->OptionValue["Workers"],"KernelExecutable"->OptionValue["KernelExecutable"],"ProgressFunction"->report];
 If[FailureQ[pool],Return[pool]];
 red=ReduceIntegrals[f,raw,pool["Equations"],"Solver"->"FiniteFlow","NumericalVerificationPoints"->{point},"ProgressFunction"->report];If[FailureQ[red],Return[red]];
 images=red["ReducedTargets"];countImages=If[scope==="HighestLoopModuloBoundary",images/._BoundaryIntegral->0,images];
 atoms=Join[support[countImages],sources[countImages]];matrix=coeff[countImages,atoms];cvars=Table[Unique["topCoefficient$"],{Length[raw]}];
 rules=FiniteFlow`FFSparseSolve[(#==0& /@ (Transpose[matrix].cvars)),Reverse[cvars],"Parameters"->f["Variables"]];
 If[!ListQ[rules],Return[fail["TopAnnihilatorSolve","FiniteFlow did not reconstruct the relations between top derivatives."]]];
 free=Complement[cvars,First /@ rules];vectors=Table[Together /@ ((cvars/.rules)/.Thread[free->UnitVector[Length[free],k]]),{k,Length[free]}];
 residuals=If[vectors==={},{},canonicalLinear /@ (vectors.images)];
 If[!If[scope==="HighestLoopModuloBoundary",FreeQ[residuals,_G],AllTrue[residuals,#===0&]],Return[fail["TopAnnihilatorResidual","A reconstructed operator has a nonzero residual in the declared counting scope."]]];
 ds=Table[Unique["topDerivative$"],{Length[f["Variables"]]}];
 operators=If[vectors==={},{},operatorNormalize[#,ds]& /@ (vectors.(Times@@(ds^#)& /@ ansatz["Exponents"]))];
 bound=TopAnnihilatorRankBound[operators,ds,f["Variables"],"TimeLimit"->OptionValue["TimeLimit"]];
 base=<|"FamilyHash"->f["Hash"],"InputHash"->Hash[{top},"SHA256"],"ImplementationHash"->$implementationHash,
  "Top"->top,"Ansatz"->ansatz,"IBPSystem"->pool,"Reduction"->red,"Operators"->operators,
  "RelationVectors"->vectors,"OperatorResiduals"->residuals,"RetainedLowerLoopSourceRows"->residuals,"Bound"->bound,"Scope"->scope,"LoopCount"->f["LoopCount"],
  "LowerLoopsCountedSeparately"->True,"NoLowerLoopSourcesDiscarded"->True,
  "DECampaignRun"->False,"FiniteBasisSelectionPerformed"->False,"Seconds"->AbsoluteTime[]-t0|>;
 If[FailureQ[bound],Return[Join[base,<|"Status"->"InsufficientAnnihilators","CertifiedUpperBound"->Missing["NotEstablished"],"IsMasterIntegralUpperBound"->False|>]]];
 proof=topBoundRowSpaceCertificate[f,pool["Equations"],red,point];If[FailureQ[proof],Return[Join[base,<|"Status"->"ExactProofFailed","Proof"->proof,"CertifiedUpperBound"->Missing["NotEstablished"],"IsMasterIntegralUpperBound"->False|>]]];
 Join[base,<|"Status"->"CertifiedTopUpperBound","Proof"->proof,"CertifiedUpperBound"->bound["UpperBound"],"IsMasterIntegralUpperBound"->True,
  "Seconds"->AbsoluteTime[]-t0,
  "LoopUpperBounds"->Association@Table[k->If[k===f["LoopCount"],bound["UpperBound"],Missing["SeparateCountRequired"]],{k,f["LoopCount"],1,-1}],
  "ScopeAssumptions"->"IBP and symmetry identities generated by the current package are valid for the supplied family; generic kinematics away from certificate denominators"|>]];
